<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BitcoderCZ.IO" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Utils/BoostUtils.cs" />
    <Compile Remove="Constants/AccountConstants.cs" />
  </ItemGroup>

</Project>
