<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Locator</AssemblyName>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <Target Name="MoveDependenciesToShared" AfterTargets="Publish" Condition="'$(UseSharedLibs)' == 'true'">

    <PropertyGroup>
      <SharedLibsDir>$([System.IO.Path]::GetFullPath('$(PublishDir)..\shared_libs'))\</SharedLibsDir>
    </PropertyGroup>

    <ItemGroup>
      <FilesToMove Include="$(PublishDir)*.dll;$(PublishDir)*.pdb" Exclude="$(PublishDir)$(TargetName).dll;$(PublishDir)$(TargetName).pdb" />
    </ItemGroup>

    <MakeDir Directories="$(SharedLibsDir)" />

    <Copy SourceFiles="@(FilesToMove)" DestinationFolder="$(SharedLibsDir)" SkipUnchangedFiles="true" Retries="5" RetryDelayMilliseconds="500" />

    <Delete Files="@(FilesToMove)" />

  </Target>

  <PropertyGroup Condition="'$(UseSharedLibs)' == 'true'">
    <DefineConstants>$(DefineConstants);USE_SHARED_LIBS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
