// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Solace.DB;
using Solace.DB.CompiledModels.Postgres;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(EarthDbContext), typeof(EarthDbContextModel))]
