// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    public static class HotbarEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(HotbarEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Items>k__BackingField")]
        public static extern ref HotbarEF.Item[] Items(HotbarEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Version>k__BackingField")]
        public static extern ref int Version(HotbarEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(HotbarEF @this);
    }
}
