// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models;
using Solace.DB.Models.Common;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class InventoryEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.InventoryEF",
                typeof(InventoryEF),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(InventoryEF).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryEF).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (InventoryEF instance) => InventoryEFUnsafeAccessors.Id(instance),
                bool (InventoryEF instance) => InventoryEFUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                InventoryEF (InventoryEF instance, Guid value) =>
                {
                    InventoryEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                InventoryEF (InventoryEF instance, Guid value) =>
                {
                    InventoryEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && InventoryEFUnsafeAccessors.Id(((InventoryEF)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : InventoryEFUnsafeAccessors.Id(((InventoryEF)(entry.Entity))))),
                Guid (IInternalEntry entry) => InventoryEFUnsafeAccessors.Id(((InventoryEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var nonStackableItemsData = runtimeEntityType.AddProperty(
                "NonStackableItemsData",
                typeof(Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>),
                propertyInfo: typeof(InventoryEF).GetProperty("NonStackableItemsData", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryEF).GetField("<NonStackableItemsData>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new NonStackableItemValueConverter());
            nonStackableItemsData.SetGetter(
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (InventoryEF instance) => InventoryEFUnsafeAccessors.NonStackableItemsData(instance),
                bool (InventoryEF instance) => InventoryEFUnsafeAccessors.NonStackableItemsData(instance) == null);
            nonStackableItemsData.SetSetter(
                InventoryEF (InventoryEF instance, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> value) =>
                {
                    InventoryEFUnsafeAccessors.NonStackableItemsData(instance) = value;
                    return instance;
                });
            nonStackableItemsData.SetMaterializationSetter(
                InventoryEF (InventoryEF instance, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> value) =>
                {
                    InventoryEFUnsafeAccessors.NonStackableItemsData(instance) = value;
                    return instance;
                });
            nonStackableItemsData.SetAccessors(
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (IInternalEntry entry) => InventoryEFUnsafeAccessors.NonStackableItemsData(((InventoryEF)(entry.Entity))),
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (IInternalEntry entry) => InventoryEFUnsafeAccessors.NonStackableItemsData(((InventoryEF)(entry.Entity))),
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (IInternalEntry entry) => entry.ReadOriginalValue<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(nonStackableItemsData, 1),
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (IInternalEntry entry) => entry.GetCurrentValue<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(nonStackableItemsData));
            nonStackableItemsData.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            nonStackableItemsData.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(
                    bool (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v1, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => v),
                keyComparer: new ValueComparer<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(
                    bool (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v1, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String),
                converter: new ValueConverter<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>, string>(
                    string (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidDictionaryGuidNonStackableItemInstance),
                    Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidDictionaryGuidNonStackableItemInstance) ?? new Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>, string>(
                        string (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidDictionaryGuidNonStackableItemInstance),
                        Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidDictionaryGuidNonStackableItemInstance) ?? new Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>())));
            nonStackableItemsData.SetComparer(new ValueComparer<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(
                bool (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> d1, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> d2) => NonStackableItemDictionaryValueComparer.OuterDictionariesEqual(d1, d2),
                int (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> d) => NonStackableItemDictionaryValueComparer.ComputeOuterHashCode(d),
                Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> (Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>> d) => d.ToDictionary(Guid (KeyValuePair<Guid, Dictionary<Guid, NonStackableItemInstance>> x) => x.Key, Dictionary<Guid, NonStackableItemInstance> (KeyValuePair<Guid, Dictionary<Guid, NonStackableItemInstance>> x) => new Dictionary<Guid, NonStackableItemInstance>(x.Value.Select(KeyValuePair<Guid, NonStackableItemInstance> (KeyValuePair<Guid, NonStackableItemInstance> item) => new KeyValuePair<Guid, NonStackableItemInstance>(item.Key, item.Value.DeepCopy()))))));
            nonStackableItemsData.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var stackableItemsData = runtimeEntityType.AddProperty(
                "StackableItemsData",
                typeof(Dictionary<Guid, int>),
                propertyInfo: typeof(InventoryEF).GetProperty("StackableItemsData", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryEF).GetField("<StackableItemsData>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new StackableItemValueConverter());
            stackableItemsData.SetGetter(
                Dictionary<Guid, int> (InventoryEF instance) => InventoryEFUnsafeAccessors.StackableItemsData(instance),
                bool (InventoryEF instance) => InventoryEFUnsafeAccessors.StackableItemsData(instance) == null);
            stackableItemsData.SetSetter(
                InventoryEF (InventoryEF instance, Dictionary<Guid, int> value) =>
                {
                    InventoryEFUnsafeAccessors.StackableItemsData(instance) = value;
                    return instance;
                });
            stackableItemsData.SetMaterializationSetter(
                InventoryEF (InventoryEF instance, Dictionary<Guid, int> value) =>
                {
                    InventoryEFUnsafeAccessors.StackableItemsData(instance) = value;
                    return instance;
                });
            stackableItemsData.SetAccessors(
                Dictionary<Guid, int> (IInternalEntry entry) => InventoryEFUnsafeAccessors.StackableItemsData(((InventoryEF)(entry.Entity))),
                Dictionary<Guid, int> (IInternalEntry entry) => InventoryEFUnsafeAccessors.StackableItemsData(((InventoryEF)(entry.Entity))),
                Dictionary<Guid, int> (IInternalEntry entry) => entry.ReadOriginalValue<Dictionary<Guid, int>>(stackableItemsData, 2),
                Dictionary<Guid, int> (IInternalEntry entry) => entry.GetCurrentValue<Dictionary<Guid, int>>(stackableItemsData));
            stackableItemsData.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            stackableItemsData.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Dictionary<Guid, int>>(
                    bool (Dictionary<Guid, int> v1, Dictionary<Guid, int> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, int> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, int> (Dictionary<Guid, int> v) => v),
                keyComparer: new ValueComparer<Dictionary<Guid, int>>(
                    bool (Dictionary<Guid, int> v1, Dictionary<Guid, int> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, int> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, int> (Dictionary<Guid, int> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String),
                converter: new ValueConverter<Dictionary<Guid, int>, string>(
                    string (Dictionary<Guid, int> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidInt32),
                    Dictionary<Guid, int> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidInt32) ?? new Dictionary<Guid, int>()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Dictionary<Guid, int>, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Dictionary<Guid, int>, string>(
                        string (Dictionary<Guid, int> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidInt32),
                        Dictionary<Guid, int> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidInt32) ?? new Dictionary<Guid, int>())));
            stackableItemsData.SetComparer(new ValueComparer<Dictionary<Guid, int>>(
                bool (Dictionary<Guid, int> a, Dictionary<Guid, int> b) => StackableItemDictionaryValueComparer.CompareDictionaries(a, b),
                int (Dictionary<Guid, int> a) => StackableItemDictionaryValueComparer.GetArrayHashCode(a),
                Dictionary<Guid, int> (Dictionary<Guid, int> a) => StackableItemDictionaryValueComparer.SnapshotDictionary(a)));
            stackableItemsData.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(int),
                propertyInfo: typeof(InventoryEF).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryEF).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0);
            version.SetGetter(
                int (InventoryEF instance) => InventoryEFUnsafeAccessors.Version(instance),
                bool (InventoryEF instance) => InventoryEFUnsafeAccessors.Version(instance) == 0);
            version.SetSetter(
                InventoryEF (InventoryEF instance, int value) =>
                {
                    InventoryEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetMaterializationSetter(
                InventoryEF (InventoryEF instance, int value) =>
                {
                    InventoryEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetAccessors(
                int (IInternalEntry entry) => InventoryEFUnsafeAccessors.Version(((InventoryEF)(entry.Entity))),
                int (IInternalEntry entry) => InventoryEFUnsafeAccessors.Version(((InventoryEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(version, 3),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(version));
            version.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            version.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Id") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var account = declaringEntityType.AddNavigation("Account",
                runtimeForeignKey,
                onDependent: true,
                typeof(Account),
                propertyInfo: typeof(InventoryEF).GetProperty("Account", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryEF).GetField("<Account>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            account.SetGetter(
                Account (InventoryEF instance) => InventoryEFUnsafeAccessors.Account(instance),
                bool (InventoryEF instance) => InventoryEFUnsafeAccessors.Account(instance) == null);
            account.SetSetter(
                InventoryEF (InventoryEF instance, Account value) =>
                {
                    InventoryEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetMaterializationSetter(
                InventoryEF (InventoryEF instance, Account value) =>
                {
                    InventoryEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetAccessors(
                Account (IInternalEntry entry) => InventoryEFUnsafeAccessors.Account(((InventoryEF)(entry.Entity))),
                Account (IInternalEntry entry) => InventoryEFUnsafeAccessors.Account(((InventoryEF)(entry.Entity))),
                null,
                Account (IInternalEntry entry) => entry.GetCurrentValue<Account>(account));
            account.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            var inventory = principalEntityType.AddNavigation("Inventory",
                runtimeForeignKey,
                onDependent: false,
                typeof(InventoryEF),
                propertyInfo: typeof(Account).GetProperty("Inventory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Account).GetField("<Inventory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            inventory.SetGetter(
                InventoryEF (Account instance) => AccountUnsafeAccessors.Inventory(instance),
                bool (Account instance) => AccountUnsafeAccessors.Inventory(instance) == null);
            inventory.SetSetter(
                Account (Account instance, InventoryEF value) =>
                {
                    AccountUnsafeAccessors.Inventory(instance) = value;
                    return instance;
                });
            inventory.SetMaterializationSetter(
                Account (Account instance, InventoryEF value) =>
                {
                    AccountUnsafeAccessors.Inventory(instance) = value;
                    return instance;
                });
            inventory.SetAccessors(
                InventoryEF (IInternalEntry entry) => AccountUnsafeAccessors.Inventory(((Account)(entry.Entity))),
                InventoryEF (IInternalEntry entry) => AccountUnsafeAccessors.Inventory(((Account)(entry.Entity))),
                null,
                InventoryEF (IInternalEntry entry) => entry.GetCurrentValue<InventoryEF>(inventory));
            inventory.SetPropertyIndexes(
                index: 5,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 6,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var nonStackableItemsData = runtimeEntityType.FindProperty("NonStackableItemsData");
            var stackableItemsData = runtimeEntityType.FindProperty("StackableItemsData");
            var version = runtimeEntityType.FindProperty("Version");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var account = runtimeEntityType.FindNavigation("Account");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((InventoryEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>, Dictionary<Guid, int>, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(nonStackableItemsData) == null ? null : ((ValueComparer<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>)(((IProperty)nonStackableItemsData).GetValueComparer())).Snapshot(source.GetCurrentValue<Dictionary<Guid, Dictionary<Guid, NonStackableItemInstance>>>(nonStackableItemsData))), (source.GetCurrentValue<Dictionary<Guid, int>>(stackableItemsData) == null ? null : ((ValueComparer<Dictionary<Guid, int>>)(((IProperty)stackableItemsData).GetValueComparer())).Snapshot(source.GetCurrentValue<Dictionary<Guid, int>>(stackableItemsData))), ((ValueComparer<int>)(((IProperty)version).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(version)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((InventoryEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), source.GetCurrentValue<Account>(account))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Inventories");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
