// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class JournalEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.JournalEF",
                typeof(JournalEF),
                baseEntityType,
                propertyCount: 3,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(JournalEF).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JournalEF).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (JournalEF instance) => JournalEFUnsafeAccessors.Id(instance),
                bool (JournalEF instance) => JournalEFUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                JournalEF (JournalEF instance, Guid value) =>
                {
                    JournalEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                JournalEF (JournalEF instance, Guid value) =>
                {
                    JournalEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && JournalEFUnsafeAccessors.Id(((JournalEF)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : JournalEFUnsafeAccessors.Id(((JournalEF)(entry.Entity))))),
                Guid (IInternalEntry entry) => JournalEFUnsafeAccessors.Id(((JournalEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var items = runtimeEntityType.AddProperty(
                "Items",
                typeof(Dictionary<Guid, JournalEF.ItemJournalEntry>),
                propertyInfo: typeof(JournalEF).GetProperty("Items", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JournalEF).GetField("<Items>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new JournalValueConverter());
            items.SetGetter(
                Dictionary<Guid, JournalEF.ItemJournalEntry> (JournalEF instance) => JournalEFUnsafeAccessors.Items(instance),
                bool (JournalEF instance) => JournalEFUnsafeAccessors.Items(instance) == null);
            items.SetSetter(
                JournalEF (JournalEF instance, Dictionary<Guid, JournalEF.ItemJournalEntry> value) =>
                {
                    JournalEFUnsafeAccessors.Items(instance) = value;
                    return instance;
                });
            items.SetMaterializationSetter(
                JournalEF (JournalEF instance, Dictionary<Guid, JournalEF.ItemJournalEntry> value) =>
                {
                    JournalEFUnsafeAccessors.Items(instance) = value;
                    return instance;
                });
            items.SetAccessors(
                Dictionary<Guid, JournalEF.ItemJournalEntry> (IInternalEntry entry) => JournalEFUnsafeAccessors.Items(((JournalEF)(entry.Entity))),
                Dictionary<Guid, JournalEF.ItemJournalEntry> (IInternalEntry entry) => JournalEFUnsafeAccessors.Items(((JournalEF)(entry.Entity))),
                Dictionary<Guid, JournalEF.ItemJournalEntry> (IInternalEntry entry) => entry.ReadOriginalValue<Dictionary<Guid, JournalEF.ItemJournalEntry>>(items, 1),
                Dictionary<Guid, JournalEF.ItemJournalEntry> (IInternalEntry entry) => entry.GetCurrentValue<Dictionary<Guid, JournalEF.ItemJournalEntry>>(items));
            items.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            items.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Dictionary<Guid, JournalEF.ItemJournalEntry>>(
                    bool (Dictionary<Guid, JournalEF.ItemJournalEntry> v1, Dictionary<Guid, JournalEF.ItemJournalEntry> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, JournalEF.ItemJournalEntry> (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => v),
                keyComparer: new ValueComparer<Dictionary<Guid, JournalEF.ItemJournalEntry>>(
                    bool (Dictionary<Guid, JournalEF.ItemJournalEntry> v1, Dictionary<Guid, JournalEF.ItemJournalEntry> v2) => object.Equals(v1, v2),
                    int (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => ((object)v).GetHashCode(),
                    Dictionary<Guid, JournalEF.ItemJournalEntry> (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String),
                converter: new ValueConverter<Dictionary<Guid, JournalEF.ItemJournalEntry>, string>(
                    string (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidItemJournalEntry),
                    Dictionary<Guid, JournalEF.ItemJournalEntry> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidItemJournalEntry) ?? new Dictionary<Guid, JournalEF.ItemJournalEntry>()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Dictionary<Guid, JournalEF.ItemJournalEntry>, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Dictionary<Guid, JournalEF.ItemJournalEntry>, string>(
                        string (Dictionary<Guid, JournalEF.ItemJournalEntry> v) => JsonSerializer.Serialize(v, DbJsonContext.Default.DictionaryGuidItemJournalEntry),
                        Dictionary<Guid, JournalEF.ItemJournalEntry> (string v) => JsonSerializer.Deserialize(v, DbJsonContext.Default.DictionaryGuidItemJournalEntry) ?? new Dictionary<Guid, JournalEF.ItemJournalEntry>())));
            items.SetComparer(new ValueComparer<Dictionary<Guid, JournalEF.ItemJournalEntry>>(
                bool (Dictionary<Guid, JournalEF.ItemJournalEntry> a, Dictionary<Guid, JournalEF.ItemJournalEntry> b) => JournalDictionaryValueComparer.CompareDictionaries(a, b),
                int (Dictionary<Guid, JournalEF.ItemJournalEntry> a) => JournalDictionaryValueComparer.GetArrayHashCode(a),
                Dictionary<Guid, JournalEF.ItemJournalEntry> (Dictionary<Guid, JournalEF.ItemJournalEntry> a) => JournalDictionaryValueComparer.SnapshotDictionary(a)));
            items.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(int),
                propertyInfo: typeof(JournalEF).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JournalEF).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0);
            version.SetGetter(
                int (JournalEF instance) => JournalEFUnsafeAccessors.Version(instance),
                bool (JournalEF instance) => JournalEFUnsafeAccessors.Version(instance) == 0);
            version.SetSetter(
                JournalEF (JournalEF instance, int value) =>
                {
                    JournalEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetMaterializationSetter(
                JournalEF (JournalEF instance, int value) =>
                {
                    JournalEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetAccessors(
                int (IInternalEntry entry) => JournalEFUnsafeAccessors.Version(((JournalEF)(entry.Entity))),
                int (IInternalEntry entry) => JournalEFUnsafeAccessors.Version(((JournalEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(version, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(version));
            version.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            version.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Id") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var account = declaringEntityType.AddNavigation("Account",
                runtimeForeignKey,
                onDependent: true,
                typeof(Account),
                propertyInfo: typeof(JournalEF).GetProperty("Account", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JournalEF).GetField("<Account>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            account.SetGetter(
                Account (JournalEF instance) => JournalEFUnsafeAccessors.Account(instance),
                bool (JournalEF instance) => JournalEFUnsafeAccessors.Account(instance) == null);
            account.SetSetter(
                JournalEF (JournalEF instance, Account value) =>
                {
                    JournalEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetMaterializationSetter(
                JournalEF (JournalEF instance, Account value) =>
                {
                    JournalEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetAccessors(
                Account (IInternalEntry entry) => JournalEFUnsafeAccessors.Account(((JournalEF)(entry.Entity))),
                Account (IInternalEntry entry) => JournalEFUnsafeAccessors.Account(((JournalEF)(entry.Entity))),
                null,
                Account (IInternalEntry entry) => entry.GetCurrentValue<Account>(account));
            account.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            var journal = principalEntityType.AddNavigation("Journal",
                runtimeForeignKey,
                onDependent: false,
                typeof(JournalEF),
                propertyInfo: typeof(Account).GetProperty("Journal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Account).GetField("<Journal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            journal.SetGetter(
                JournalEF (Account instance) => AccountUnsafeAccessors.Journal(instance),
                bool (Account instance) => AccountUnsafeAccessors.Journal(instance) == null);
            journal.SetSetter(
                Account (Account instance, JournalEF value) =>
                {
                    AccountUnsafeAccessors.Journal(instance) = value;
                    return instance;
                });
            journal.SetMaterializationSetter(
                Account (Account instance, JournalEF value) =>
                {
                    AccountUnsafeAccessors.Journal(instance) = value;
                    return instance;
                });
            journal.SetAccessors(
                JournalEF (IInternalEntry entry) => AccountUnsafeAccessors.Journal(((Account)(entry.Entity))),
                JournalEF (IInternalEntry entry) => AccountUnsafeAccessors.Journal(((Account)(entry.Entity))),
                null,
                JournalEF (IInternalEntry entry) => entry.GetCurrentValue<JournalEF>(journal));
            journal.SetPropertyIndexes(
                index: 6,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 7,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var items = runtimeEntityType.FindProperty("Items");
            var version = runtimeEntityType.FindProperty("Version");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var account = runtimeEntityType.FindNavigation("Account");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((JournalEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Dictionary<Guid, JournalEF.ItemJournalEntry>, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<Dictionary<Guid, JournalEF.ItemJournalEntry>>(items) == null ? null : ((ValueComparer<Dictionary<Guid, JournalEF.ItemJournalEntry>>)(((IProperty)items).GetValueComparer())).Snapshot(source.GetCurrentValue<Dictionary<Guid, JournalEF.ItemJournalEntry>>(items))), ((ValueComparer<int>)(((IProperty)version).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(version)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((JournalEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), source.GetCurrentValue<Account>(account))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 3,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 3,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Journals");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
