// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class RedeemedTappablesEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.RedeemedTappablesEF",
                typeof(RedeemedTappablesEF),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 2,
                foreignKeyCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(RedeemedTappablesEF).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedeemedTappablesEF).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Id(instance),
                bool (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, Guid value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, Guid value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && RedeemedTappablesEFUnsafeAccessors.Id(((RedeemedTappablesEF)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : RedeemedTappablesEFUnsafeAccessors.Id(((RedeemedTappablesEF)(entry.Entity))))),
                Guid (IInternalEntry entry) => RedeemedTappablesEFUnsafeAccessors.Id(((RedeemedTappablesEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(int),
                propertyInfo: typeof(RedeemedTappablesEF).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedeemedTappablesEF).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0);
            version.SetGetter(
                int (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Version(instance),
                bool (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Version(instance) == 0);
            version.SetSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, int value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetMaterializationSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, int value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Version(instance) = value;
                    return instance;
                });
            version.SetAccessors(
                int (IInternalEntry entry) => RedeemedTappablesEFUnsafeAccessors.Version(((RedeemedTappablesEF)(entry.Entity))),
                int (IInternalEntry entry) => RedeemedTappablesEFUnsafeAccessors.Version(((RedeemedTappablesEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(version, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(version));
            version.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            version.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Id") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var account = declaringEntityType.AddNavigation("Account",
                runtimeForeignKey,
                onDependent: true,
                typeof(Account),
                propertyInfo: typeof(RedeemedTappablesEF).GetProperty("Account", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedeemedTappablesEF).GetField("<Account>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            account.SetGetter(
                Account (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Account(instance),
                bool (RedeemedTappablesEF instance) => RedeemedTappablesEFUnsafeAccessors.Account(instance) == null);
            account.SetSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, Account value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetMaterializationSetter(
                RedeemedTappablesEF (RedeemedTappablesEF instance, Account value) =>
                {
                    RedeemedTappablesEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetAccessors(
                Account (IInternalEntry entry) => RedeemedTappablesEFUnsafeAccessors.Account(((RedeemedTappablesEF)(entry.Entity))),
                Account (IInternalEntry entry) => RedeemedTappablesEFUnsafeAccessors.Account(((RedeemedTappablesEF)(entry.Entity))),
                null,
                Account (IInternalEntry entry) => entry.GetCurrentValue<Account>(account));
            account.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            var redeemedTappables = principalEntityType.AddNavigation("RedeemedTappables",
                runtimeForeignKey,
                onDependent: false,
                typeof(RedeemedTappablesEF),
                propertyInfo: typeof(Account).GetProperty("RedeemedTappables", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Account).GetField("<RedeemedTappables>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            redeemedTappables.SetGetter(
                RedeemedTappablesEF (Account instance) => AccountUnsafeAccessors.RedeemedTappables(instance),
                bool (Account instance) => AccountUnsafeAccessors.RedeemedTappables(instance) == null);
            redeemedTappables.SetSetter(
                Account (Account instance, RedeemedTappablesEF value) =>
                {
                    AccountUnsafeAccessors.RedeemedTappables(instance) = value;
                    return instance;
                });
            redeemedTappables.SetMaterializationSetter(
                Account (Account instance, RedeemedTappablesEF value) =>
                {
                    AccountUnsafeAccessors.RedeemedTappables(instance) = value;
                    return instance;
                });
            redeemedTappables.SetAccessors(
                RedeemedTappablesEF (IInternalEntry entry) => AccountUnsafeAccessors.RedeemedTappables(((Account)(entry.Entity))),
                RedeemedTappablesEF (IInternalEntry entry) => AccountUnsafeAccessors.RedeemedTappables(((Account)(entry.Entity))),
                null,
                RedeemedTappablesEF (IInternalEntry entry) => entry.GetCurrentValue<RedeemedTappablesEF>(redeemedTappables));
            redeemedTappables.SetPropertyIndexes(
                index: 8,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 9,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var version = runtimeEntityType.FindProperty("Version");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var account = runtimeEntityType.FindNavigation("Account");
            var tappables = runtimeEntityType.FindNavigation("Tappables");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((RedeemedTappablesEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<int>)(((IProperty)version).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(version)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((RedeemedTappablesEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), source.GetCurrentValue<Account>(account), source.GetCurrentValue<Dictionary<Guid, long>>(tappables))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RedeemedTappables");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
