// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Global;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    public static class SharedBuildplateEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref Guid AccountId(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BuildplateLastModifed>k__BackingField")]
        public static extern ref long BuildplateLastModifed(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Created>k__BackingField")]
        public static extern ref long Created(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Hotbar>k__BackingField")]
        public static extern ref SharedBuildplateEF.HotbarItem[] Hotbar(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastViewed>k__BackingField")]
        public static extern ref long LastViewed(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Night>k__BackingField")]
        public static extern ref bool Night(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NumberOfTimesViewed>k__BackingField")]
        public static extern ref int NumberOfTimesViewed(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Offset>k__BackingField")]
        public static extern ref int Offset(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Scale>k__BackingField")]
        public static extern ref int Scale(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ServerDataObjectId>k__BackingField")]
        public static extern ref string ServerDataObjectId(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref int Size(SharedBuildplateEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(SharedBuildplateEF @this);
    }
}
