// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels.Postgres
{
    public static class TokensEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(TokensEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tokens>k__BackingField")]
        public static extern ref Dictionary<string, TokensEF.Token> Tokens(TokensEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Version>k__BackingField")]
        public static extern ref int Version(TokensEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(TokensEF @this);
    }
}
