<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BitcoderCZ.Utils" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.DB.Earth/Solace.DB.Earth.csproj" />
  </ItemGroup>

</Project>
