<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BitcoderCZ.Utils" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.Db.Earth/Solace.Db.Earth.csproj" />
  </ItemGroup>

</Project>
