<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f7a353f3-b007-4d60-b616-4aa04a086e5f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" Version="13.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.AdminPanel/Solace.AdminPanel.csproj" />
    <ProjectReference Include="../Solace.ApiServer/Solace.ApiServer.csproj" />
    <ProjectReference Include="../Solace.Buildplate/Solace.Buildplate.csproj" />
    <ProjectReference Include="../Solace.EventBus.Server/Solace.EventBus.Server.csproj" />
    <ProjectReference Include="../Solace.Locator/Solace.Locator.csproj" />
    <ProjectReference Include="../Solace.ObjectStore.Server/Solace.ObjectStore.Server.csproj" />
    <ProjectReference Include="../Solace.TappablesGenerator/Solace.TappablesGenerator.csproj" />
    <ProjectReference Include="../Solace.TileRenderer/Solace.TileRenderer.csproj" />
  </ItemGroup>

</Project>
