// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB;

#nullable disable

namespace Solace.DB.Postgres.Migrations
{
    [DbContext(typeof(EarthDbContext))]
    [Migration("20260614083135_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solace.DB.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.EncounterBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EncounterBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.Secret", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.SharedBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("BuildplateLastModifed")
                        .HasColumnType("bigint");

                    b.Property<long>("Created")
                        .HasColumnType("bigint");

                    b.Property<string>("Hotbar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastViewed")
                        .HasColumnType("bigint");

                    b.Property<bool>("Night")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfTimesViewed")
                        .HasColumnType("integer");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SharedBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.TemplateBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Night")
                        .HasColumnType("boolean");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TemplateBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.Tile", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ObjectStoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ActivityLogEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BoostsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveBoosts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Boosts");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastModified")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Night")
                        .HasColumnType("boolean");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PlayerBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.HotbarEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hotbars");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.InventoryEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("NonStackableItemsData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackableItemsData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.JournalEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ProfileEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.RedeemedTappablesEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RedeemedTappables");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.TokensEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CraftingSlots");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SmeltingSlots");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.SharedBuildplateEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithMany("SharedBuildplates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ActivityLogEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("ActivityLog")
                        .HasForeignKey("Solace.DB.Models.Player.ActivityLogEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BoostsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Boosts")
                        .HasForeignKey("Solace.DB.Models.Player.BoostsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BuildplateEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithMany("Buildplates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.HotbarEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Hotbar")
                        .HasForeignKey("Solace.DB.Models.Player.HotbarEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.InventoryEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Inventory")
                        .HasForeignKey("Solace.DB.Models.Player.InventoryEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.JournalEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Journal")
                        .HasForeignKey("Solace.DB.Models.Player.JournalEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ProfileEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("Solace.DB.Models.Player.ProfileEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Solace.DB.Models.Player.Rubies", "Rubies", b1 =>
                        {
                            b1.Property<Guid>("ProfileEFId");

                            b1.Property<int>("Earned");

                            b1.Property<int>("Purchased");

                            b1.HasKey("ProfileEFId");

                            b1.ToTable("Profiles");

                            b1
                                .ToJson("Rubies")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProfileEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Rubies")
                        .IsRequired();
                });

            modelBuilder.Entity("Solace.DB.Models.Player.RedeemedTappablesEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("RedeemedTappables")
                        .HasForeignKey("Solace.DB.Models.Player.RedeemedTappablesEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("System.Collections.Generic.Dictionary<System.Guid, long>", "Tappables", b1 =>
                        {
                            b1.Property<Guid>("RedeemedTappablesEFId");

                            b1.HasKey("RedeemedTappablesEFId");

                            b1.ToTable("RedeemedTappables");

                            b1
                                .ToJson("Tappables")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RedeemedTappablesEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Tappables");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.TokensEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Tokens")
                        .HasForeignKey("Solace.DB.Models.Player.TokensEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("CraftingSlots")
                        .HasForeignKey("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("SmeltingSlots")
                        .HasForeignKey("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Account", b =>
                {
                    b.Navigation("ActivityLog");

                    b.Navigation("Boosts");

                    b.Navigation("Buildplates");

                    b.Navigation("CraftingSlots");

                    b.Navigation("Hotbar");

                    b.Navigation("Inventory");

                    b.Navigation("Journal");

                    b.Navigation("Profile");

                    b.Navigation("RedeemedTappables");

                    b.Navigation("SharedBuildplates");

                    b.Navigation("SmeltingSlots");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
