<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ServerSetup</AssemblyName>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.Buildplate.Common/Solace.Buildplate.Common.csproj" />
    <ProjectReference Include="../Solace.Common/Solace.Common.csproj" />
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
