<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <AssemblyName>BuildplateUpdater</AssemblyName>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cyotek.Data.Nbt" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.Common/Solace.Common.csproj" />
    <ProjectReference Include="../Solace.EventBus.Client/Solace.EventBus.Client.csproj" />
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
    <ProjectReference Include="../Solace.StaticData/Solace.StaticData.csproj" />
  </ItemGroup>

</Project>
