<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.Analyzer/Solace.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Solace.Common.Asp/Solace.Common.Asp.csproj" />
    <ProjectReference Include="../Solace.Common/Solace.Common.csproj" />
    <ProjectReference Include="../Solace.Db.Earth/Solace.Db.Earth.csproj" />
    <ProjectReference Include="../Solace.Db/Solace.Db.csproj" />
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
    <ProjectReference Include="../Solace.StaticData/Solace.StaticData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Solace.Common/Constants/AccountConstants.cs" Link="AccountConstants.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Immediate.Apis" />
    <PackageReference Include="Immediate.Validations" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="Nager.PublicSuffix" />
    <PackageReference Include="OData2Linq" />
  </ItemGroup>

  <ItemGroup>
    <None Update="public_suffix_list.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
