<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.Common.Asp/Solace.Common.Asp.csproj" />
    <ProjectReference Include="../Solace.Common/Solace.Common.csproj" />
    <ProjectReference Include="../Solace.DB/Solace.DB.csproj" />
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Immediate.Apis" />
    <PackageReference Include="Immediate.Validations" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <None Update="public_suffix_list.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
