// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class AccountVersionsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Boosts>k__BackingField")]
        public static extern ref int Boosts(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Buildplates>k__BackingField")]
        public static extern ref int Buildplates(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Challenges>k__BackingField")]
        public static extern ref int Challenges(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Crafting>k__BackingField")]
        public static extern ref int Crafting(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Inventory>k__BackingField")]
        public static extern ref int Inventory(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Journal>k__BackingField")]
        public static extern ref int Journal(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Profile>k__BackingField")]
        public static extern ref int Profile(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Smelting>k__BackingField")]
        public static extern ref int Smelting(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tokens>k__BackingField")]
        public static extern ref int Tokens(AccountVersions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(AccountVersions @this);
    }
}
