// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AccountVersionsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.AccountVersions",
                typeof(AccountVersions),
                baseEntityType,
                propertyCount: 10,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AccountVersions).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (AccountVersions instance) => AccountVersionsUnsafeAccessors.Id(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                AccountVersions (AccountVersions instance, Guid value) =>
                {
                    AccountVersionsUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, Guid value) =>
                {
                    AccountVersionsUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && AccountVersionsUnsafeAccessors.Id(((AccountVersions)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : AccountVersionsUnsafeAccessors.Id(((AccountVersions)(entry.Entity))))),
                Guid (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Id(((AccountVersions)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var boosts = runtimeEntityType.AddProperty(
                "Boosts",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Boosts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Boosts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            boosts.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Boosts(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Boosts(instance) == 0);
            boosts.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Boosts(instance) = value;
                    return instance;
                });
            boosts.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Boosts(instance) = value;
                    return instance;
                });
            boosts.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Boosts(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Boosts(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(boosts, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(boosts));
            boosts.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            boosts.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            boosts.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var buildplates = runtimeEntityType.AddProperty(
                "Buildplates",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Buildplates", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Buildplates>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            buildplates.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Buildplates(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Buildplates(instance) == 0);
            buildplates.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Buildplates(instance) = value;
                    return instance;
                });
            buildplates.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Buildplates(instance) = value;
                    return instance;
                });
            buildplates.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Buildplates(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Buildplates(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(buildplates, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(buildplates));
            buildplates.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            buildplates.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            buildplates.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var challenges = runtimeEntityType.AddProperty(
                "Challenges",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Challenges", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Challenges>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            challenges.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Challenges(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Challenges(instance) == 0);
            challenges.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Challenges(instance) = value;
                    return instance;
                });
            challenges.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Challenges(instance) = value;
                    return instance;
                });
            challenges.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Challenges(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Challenges(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(challenges, 3),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(challenges));
            challenges.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            challenges.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            challenges.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var crafting = runtimeEntityType.AddProperty(
                "Crafting",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Crafting", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Crafting>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            crafting.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Crafting(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Crafting(instance) == 0);
            crafting.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Crafting(instance) = value;
                    return instance;
                });
            crafting.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Crafting(instance) = value;
                    return instance;
                });
            crafting.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Crafting(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Crafting(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(crafting, 4),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(crafting));
            crafting.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            crafting.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            crafting.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var inventory = runtimeEntityType.AddProperty(
                "Inventory",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Inventory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Inventory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            inventory.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Inventory(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Inventory(instance) == 0);
            inventory.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Inventory(instance) = value;
                    return instance;
                });
            inventory.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Inventory(instance) = value;
                    return instance;
                });
            inventory.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Inventory(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Inventory(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(inventory, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(inventory));
            inventory.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            inventory.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            inventory.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var journal = runtimeEntityType.AddProperty(
                "Journal",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Journal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Journal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            journal.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Journal(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Journal(instance) == 0);
            journal.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Journal(instance) = value;
                    return instance;
                });
            journal.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Journal(instance) = value;
                    return instance;
                });
            journal.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Journal(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Journal(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(journal, 6),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(journal));
            journal.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            journal.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            journal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var profile = runtimeEntityType.AddProperty(
                "Profile",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Profile", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Profile>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            profile.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Profile(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Profile(instance) == 0);
            profile.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Profile(instance) = value;
                    return instance;
                });
            profile.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Profile(instance) = value;
                    return instance;
                });
            profile.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Profile(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Profile(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(profile, 7),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(profile));
            profile.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            profile.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            profile.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var smelting = runtimeEntityType.AddProperty(
                "Smelting",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Smelting", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Smelting>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            smelting.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Smelting(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Smelting(instance) == 0);
            smelting.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Smelting(instance) = value;
                    return instance;
                });
            smelting.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Smelting(instance) = value;
                    return instance;
                });
            smelting.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Smelting(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Smelting(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(smelting, 8),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(smelting));
            smelting.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            smelting.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            smelting.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var tokens = runtimeEntityType.AddProperty(
                "Tokens",
                typeof(int),
                propertyInfo: typeof(AccountVersions).GetProperty("Tokens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Tokens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            tokens.SetGetter(
                int (AccountVersions instance) => AccountVersionsUnsafeAccessors.Tokens(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Tokens(instance) == 0);
            tokens.SetSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Tokens(instance) = value;
                    return instance;
                });
            tokens.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, int value) =>
                {
                    AccountVersionsUnsafeAccessors.Tokens(instance) = value;
                    return instance;
                });
            tokens.SetAccessors(
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Tokens(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Tokens(((AccountVersions)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(tokens, 9),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(tokens));
            tokens.SetPropertyIndexes(
                index: 9,
                originalValueIndex: 9,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tokens.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            tokens.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Id") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var account = declaringEntityType.AddNavigation("Account",
                runtimeForeignKey,
                onDependent: true,
                typeof(Account),
                propertyInfo: typeof(AccountVersions).GetProperty("Account", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AccountVersions).GetField("<Account>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            account.SetGetter(
                Account (AccountVersions instance) => AccountVersionsUnsafeAccessors.Account(instance),
                bool (AccountVersions instance) => AccountVersionsUnsafeAccessors.Account(instance) == null);
            account.SetSetter(
                AccountVersions (AccountVersions instance, Account value) =>
                {
                    AccountVersionsUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetMaterializationSetter(
                AccountVersions (AccountVersions instance, Account value) =>
                {
                    AccountVersionsUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetAccessors(
                Account (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Account(((AccountVersions)(entry.Entity))),
                Account (IInternalEntry entry) => AccountVersionsUnsafeAccessors.Account(((AccountVersions)(entry.Entity))),
                null,
                Account (IInternalEntry entry) => entry.GetCurrentValue<Account>(account));
            account.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            var accountVersions = principalEntityType.AddNavigation("AccountVersions",
                runtimeForeignKey,
                onDependent: false,
                typeof(AccountVersions),
                propertyInfo: typeof(Account).GetProperty("AccountVersions", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Account).GetField("<AccountVersions>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            accountVersions.SetGetter(
                AccountVersions (Account instance) => AccountUnsafeAccessors.AccountVersions(instance),
                bool (Account instance) => AccountUnsafeAccessors.AccountVersions(instance) == null);
            accountVersions.SetSetter(
                Account (Account instance, AccountVersions value) =>
                {
                    AccountUnsafeAccessors.AccountVersions(instance) = value;
                    return instance;
                });
            accountVersions.SetMaterializationSetter(
                Account (Account instance, AccountVersions value) =>
                {
                    AccountUnsafeAccessors.AccountVersions(instance) = value;
                    return instance;
                });
            accountVersions.SetAccessors(
                AccountVersions (IInternalEntry entry) => AccountUnsafeAccessors.AccountVersions(((Account)(entry.Entity))),
                AccountVersions (IInternalEntry entry) => AccountUnsafeAccessors.AccountVersions(((Account)(entry.Entity))),
                null,
                AccountVersions (IInternalEntry entry) => entry.GetCurrentValue<AccountVersions>(accountVersions));
            accountVersions.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var boosts = runtimeEntityType.FindProperty("Boosts");
            var buildplates = runtimeEntityType.FindProperty("Buildplates");
            var challenges = runtimeEntityType.FindProperty("Challenges");
            var crafting = runtimeEntityType.FindProperty("Crafting");
            var inventory = runtimeEntityType.FindProperty("Inventory");
            var journal = runtimeEntityType.FindProperty("Journal");
            var profile = runtimeEntityType.FindProperty("Profile");
            var smelting = runtimeEntityType.FindProperty("Smelting");
            var tokens = runtimeEntityType.FindProperty("Tokens");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var account = runtimeEntityType.FindNavigation("Account");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AccountVersions)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int, int, int, int, int, int, int, int, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<int>)(((IProperty)boosts).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(boosts)), ((ValueComparer<int>)(((IProperty)buildplates).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(buildplates)), ((ValueComparer<int>)(((IProperty)challenges).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(challenges)), ((ValueComparer<int>)(((IProperty)crafting).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(crafting)), ((ValueComparer<int>)(((IProperty)inventory).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(inventory)), ((ValueComparer<int>)(((IProperty)journal).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(journal)), ((ValueComparer<int>)(((IProperty)profile).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(profile)), ((ValueComparer<int>)(((IProperty)smelting).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(smelting)), ((ValueComparer<int>)(((IProperty)tokens).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(tokens)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AccountVersions)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), source.GetCurrentValue<Account>(account))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 10,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 10,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AccountVersions");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
