// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Global;
using Solace.DB.Models.Player;
using Solace.DB.Models.Player.Workshop;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class AccountUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedDate>k__BackingField")]
        public static extern ref long CreatedDate(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FirstName>k__BackingField")]
        public static extern ref string FirstName(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsSkinSlim>k__BackingField")]
        public static extern ref bool IsSkinSlim(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastName>k__BackingField")]
        public static extern ref string LastName(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PasswordHash>k__BackingField")]
        public static extern ref byte[] PasswordHash(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PasswordSalt>k__BackingField")]
        public static extern ref byte[] PasswordSalt(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProfilePictureUrl>k__BackingField")]
        public static extern ref string ProfilePictureUrl(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SkinImageData>k__BackingField")]
        public static extern ref byte[] SkinImageData(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Username>k__BackingField")]
        public static extern ref string Username(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountVersions>k__BackingField")]
        public static extern ref AccountVersions AccountVersions(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActivityLogs>k__BackingField")]
        public static extern ref ICollection<ActivityLogEntryEF> ActivityLogs(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Boosts>k__BackingField")]
        public static extern ref BoostsEF Boosts(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Buildplates>k__BackingField")]
        public static extern ref ICollection<BuildplateEF> Buildplates(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CraftingSlots>k__BackingField")]
        public static extern ref CraftingSlotsEF CraftingSlots(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Hotbar>k__BackingField")]
        public static extern ref HotbarEF Hotbar(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<JournalEntries>k__BackingField")]
        public static extern ref ICollection<ItemJournalEntryEF> JournalEntries(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NonStackableItems>k__BackingField")]
        public static extern ref ICollection<NonStackableItemInstanceEF> NonStackableItems(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Profile>k__BackingField")]
        public static extern ref ProfileEF Profile(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RedeemedTappables>k__BackingField")]
        public static extern ref ICollection<RedeemedTappableEF> RedeemedTappables(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SharedBuildplates>k__BackingField")]
        public static extern ref ICollection<SharedBuildplateEF> SharedBuildplates(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SmeltingSlots>k__BackingField")]
        public static extern ref SmeltingSlotsEF SmeltingSlots(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StackableItems>k__BackingField")]
        public static extern ref ICollection<StackableItemEF> StackableItems(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tokens>k__BackingField")]
        public static extern ref ICollection<TokenEF> Tokens(Account @this);
    }
}
