// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using Solace.DB.Models.Player.Workshop;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CraftingSlotEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.Workshop.CraftingSlotEF",
                typeof(CraftingSlotEF),
                baseEntityType,
                propertyCount: 3,
                foreignKeyCount: 1,
                keyCount: 1);

            var craftingSlotsEFId = runtimeEntityType.AddProperty(
                "CraftingSlotsEFId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            craftingSlotsEFId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<Guid>(0) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : entry.ReadShadowValue<Guid>(0))),
                Guid (IInternalEntry entry) => entry.ReadShadowValue<Guid>(0),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(craftingSlotsEFId, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(craftingSlotsEFId, 0));
            craftingSlotsEFId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            craftingSlotsEFId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            craftingSlotsEFId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(craftingSlotsEFId));
            craftingSlotsEFId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var __synthesizedOrdinal = runtimeEntityType.AddProperty(
                "__synthesizedOrdinal",
                typeof(int),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            __synthesizedOrdinal.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && entry.ReadShadowValue<int>(1) == 0 ? entry.ReadTemporaryValue<int>(1) : entry.ReadShadowValue<int>(1))),
                int (IInternalEntry entry) => entry.ReadShadowValue<int>(1),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(__synthesizedOrdinal, 1),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(__synthesizedOrdinal, 1));
            __synthesizedOrdinal.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            __synthesizedOrdinal.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            __synthesizedOrdinal.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(__synthesizedOrdinal));
            __synthesizedOrdinal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var locked = runtimeEntityType.AddProperty(
                "Locked",
                typeof(bool),
                propertyInfo: typeof(CraftingSlotEF).GetProperty("Locked", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CraftingSlotEF).GetField("<Locked>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            locked.SetGetter(
                bool (CraftingSlotEF instance) => CraftingSlotEFUnsafeAccessors.Locked(instance),
                bool (CraftingSlotEF instance) => CraftingSlotEFUnsafeAccessors.Locked(instance) == false);
            locked.SetSetter(
                CraftingSlotEF (CraftingSlotEF instance, bool value) =>
                {
                    CraftingSlotEFUnsafeAccessors.Locked(instance) = value;
                    return instance;
                });
            locked.SetMaterializationSetter(
                CraftingSlotEF (CraftingSlotEF instance, bool value) =>
                {
                    CraftingSlotEFUnsafeAccessors.Locked(instance) = value;
                    return instance;
                });
            locked.SetAccessors(
                bool (IInternalEntry entry) => CraftingSlotEFUnsafeAccessors.Locked(((CraftingSlotEF)(entry.Entity))),
                bool (IInternalEntry entry) => CraftingSlotEFUnsafeAccessors.Locked(((CraftingSlotEF)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(locked, 2),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(locked));
            locked.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            locked.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            locked.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { craftingSlotsEFId, __synthesizedOrdinal });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CraftingSlotsEFId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var slots = principalEntityType.AddNavigation("Slots",
                runtimeForeignKey,
                onDependent: false,
                typeof(CraftingSlotEF[]),
                propertyInfo: typeof(CraftingSlotsEF).GetProperty("Slots", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CraftingSlotsEF).GetField("<Slots>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            slots.SetGetter(
                CraftingSlotEF[] (CraftingSlotsEF instance) => CraftingSlotsEFUnsafeAccessors.Slots(instance),
                bool (CraftingSlotsEF instance) => CraftingSlotsEFUnsafeAccessors.Slots(instance) == null);
            slots.SetSetter(
                CraftingSlotsEF (CraftingSlotsEF instance, CraftingSlotEF[] value) =>
                {
                    CraftingSlotsEFUnsafeAccessors.Slots(instance) = value;
                    return instance;
                });
            slots.SetMaterializationSetter(
                CraftingSlotsEF (CraftingSlotsEF instance, CraftingSlotEF[] value) =>
                {
                    CraftingSlotsEFUnsafeAccessors.Slots(instance) = value;
                    return instance;
                });
            slots.SetAccessors(
                CraftingSlotEF[] (IInternalEntry entry) => CraftingSlotsEFUnsafeAccessors.Slots(((CraftingSlotsEF)(entry.Entity))),
                CraftingSlotEF[] (IInternalEntry entry) => CraftingSlotsEFUnsafeAccessors.Slots(((CraftingSlotsEF)(entry.Entity))),
                null,
                CraftingSlotEF[] (IInternalEntry entry) => entry.GetCurrentValue<CraftingSlotEF[]>(slots));
            slots.SetPropertyIndexes(
                index: 1,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            slots.SetCollectionAccessor<CraftingSlotsEF, CraftingSlotEF[], CraftingSlotEF>(
                CraftingSlotEF[] (CraftingSlotsEF entity) => CraftingSlotsEFUnsafeAccessors.Slots(entity),
                (CraftingSlotsEF entity, CraftingSlotEF[] collection) => CraftingSlotsEFUnsafeAccessors.Slots(entity) = ((CraftingSlotEF[])collection),
                (CraftingSlotsEF entity, CraftingSlotEF[] collection) => CraftingSlotsEFUnsafeAccessors.Slots(entity) = ((CraftingSlotEF[])collection),
                null,
                null);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var craftingSlotsEFId = runtimeEntityType.FindProperty("CraftingSlotsEFId");
            var __synthesizedOrdinal = runtimeEntityType.FindProperty("__synthesizedOrdinal");
            var locked = runtimeEntityType.FindProperty("Locked");
            var key = runtimeEntityType.FindKey(new[] { craftingSlotsEFId, __synthesizedOrdinal });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((CraftingSlotEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int, bool>(((ValueComparer<Guid>)(((IProperty)craftingSlotsEFId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(craftingSlotsEFId)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(__synthesizedOrdinal)), ((ValueComparer<bool>)(((IProperty)locked).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(locked)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, int>(((ValueComparer<Guid>)(((IProperty)craftingSlotsEFId).GetValueComparer())).Snapshot(default(Guid)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, int>(default(Guid), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<Guid, int>((source.ContainsKey("CraftingSlotsEFId") ? ((Guid)(source["CraftingSlotsEFId"])) : new Guid("00000000-0000-0000-0000-000000000000")), (source.ContainsKey("__synthesizedOrdinal") ? ((int)(source["__synthesizedOrdinal"])) : 0)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, int>(default(Guid), default(int)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((CraftingSlotEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int>(((ValueComparer<Guid>)(((IProperty)craftingSlotsEFId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(craftingSlotsEFId)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(__synthesizedOrdinal)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 3,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 3,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:ContainerColumnName", "Slots");
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CraftingSlots");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
