// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using Solace.DB.Models;
using Solace.DB.Models.Common;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DailyLoginTokenEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.DailyLoginToken",
                typeof(DailyLoginTokenEF),
                baseEntityType,
                discriminatorProperty: "token_type",
                discriminatorValue: "daily_login",
                propertyCount: 3);

            var claimed = runtimeEntityType.AddProperty(
                "Claimed",
                typeof(bool),
                propertyInfo: typeof(DailyLoginTokenEF).GetProperty("Claimed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailyLoginTokenEF).GetField("<Claimed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            claimed.SetGetter(
                bool (DailyLoginTokenEF instance) => DailyLoginTokenUnsafeAccessors.Claimed(instance),
                bool (DailyLoginTokenEF instance) => DailyLoginTokenUnsafeAccessors.Claimed(instance) == false);
            claimed.SetSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, bool value) =>
                {
                    DailyLoginTokenUnsafeAccessors.Claimed(instance) = value;
                    return instance;
                });
            claimed.SetMaterializationSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, bool value) =>
                {
                    DailyLoginTokenUnsafeAccessors.Claimed(instance) = value;
                    return instance;
                });
            claimed.SetAccessors(
                bool (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.Claimed(((DailyLoginTokenEF)(entry.Entity))),
                bool (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.Claimed(((DailyLoginTokenEF)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(claimed, 3),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(claimed));
            claimed.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            claimed.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            claimed.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var claimedOn = runtimeEntityType.AddProperty(
                "ClaimedOn",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(DailyLoginTokenEF).GetProperty("ClaimedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailyLoginTokenEF).GetField("<ClaimedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            claimedOn.SetGetter(
                DateTimeOffset? (DailyLoginTokenEF instance) => DailyLoginTokenUnsafeAccessors.ClaimedOn(instance),
                bool (DailyLoginTokenEF instance) => !(DailyLoginTokenUnsafeAccessors.ClaimedOn(instance).HasValue));
            claimedOn.SetSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, DateTimeOffset? value) =>
                {
                    DailyLoginTokenUnsafeAccessors.ClaimedOn(instance) = value;
                    return instance;
                });
            claimedOn.SetMaterializationSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, DateTimeOffset? value) =>
                {
                    DailyLoginTokenUnsafeAccessors.ClaimedOn(instance) = value;
                    return instance;
                });
            claimedOn.SetAccessors(
                DateTimeOffset? (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.ClaimedOn(((DailyLoginTokenEF)(entry.Entity))),
                DateTimeOffset? (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.ClaimedOn(((DailyLoginTokenEF)(entry.Entity))),
                DateTimeOffset? (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset?>(claimedOn, 4),
                DateTimeOffset? (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset?>(claimedOn));
            claimedOn.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            claimedOn.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                keyComparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                providerValueComparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                clrType: typeof(DateTimeOffset),
                jsonValueReaderWriter: new NpgsqlTimestampTzTypeMapping.NpgsqlJsonTimestampTzDateTimeOffsetReaderWriter());
            claimedOn.SetComparer(new NullableValueComparer<DateTimeOffset>(claimedOn.TypeMapping.Comparer));
            claimedOn.SetKeyComparer(new NullableValueComparer<DateTimeOffset>(claimedOn.TypeMapping.KeyComparer));
            claimedOn.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var date = runtimeEntityType.AddProperty(
                "Date",
                typeof(DateOnly),
                propertyInfo: typeof(DailyLoginTokenEF).GetProperty("Date", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailyLoginTokenEF).GetField("<Date>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            date.SetGetter(
                DateOnly (DailyLoginTokenEF instance) => DailyLoginTokenUnsafeAccessors.Date(instance),
                bool (DailyLoginTokenEF instance) => DailyLoginTokenUnsafeAccessors.Date(instance) == default(DateOnly));
            date.SetSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, DateOnly value) =>
                {
                    DailyLoginTokenUnsafeAccessors.Date(instance) = value;
                    return instance;
                });
            date.SetMaterializationSetter(
                DailyLoginTokenEF (DailyLoginTokenEF instance, DateOnly value) =>
                {
                    DailyLoginTokenUnsafeAccessors.Date(instance) = value;
                    return instance;
                });
            date.SetAccessors(
                DateOnly (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.Date(((DailyLoginTokenEF)(entry.Entity))),
                DateOnly (IInternalEntry entry) => DailyLoginTokenUnsafeAccessors.Date(((DailyLoginTokenEF)(entry.Entity))),
                DateOnly (IInternalEntry entry) => entry.ReadOriginalValue<DateOnly>(date, 5),
                DateOnly (IInternalEntry entry) => entry.GetCurrentValue<DateOnly>(date));
            date.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            date.TypeMapping = NpgsqlDateOnlyTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateOnly>(
                    bool (DateOnly v1, DateOnly v2) => v1.Equals(v2),
                    int (DateOnly v) => ((object)v).GetHashCode(),
                    DateOnly (DateOnly v) => v),
                keyComparer: new ValueComparer<DateOnly>(
                    bool (DateOnly v1, DateOnly v2) => v1.Equals(v2),
                    int (DateOnly v) => ((object)v).GetHashCode(),
                    DateOnly (DateOnly v) => v),
                providerValueComparer: new ValueComparer<DateOnly>(
                    bool (DateOnly v1, DateOnly v2) => v1.Equals(v2),
                    int (DateOnly v) => ((object)v).GetHashCode(),
                    DateOnly (DateOnly v) => v));
            date.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var accountId = runtimeEntityType.FindProperty("AccountId");
            var tokenId = runtimeEntityType.FindProperty("TokenId");
            var token_type = runtimeEntityType.FindProperty("token_type");
            var claimed = runtimeEntityType.FindProperty("Claimed");
            var claimedOn = runtimeEntityType.FindProperty("ClaimedOn");
            var date = runtimeEntityType.FindProperty("Date");
            var account = runtimeEntityType.FindNavigation("Account");
            var rewards = runtimeEntityType.FindNavigation("Rewards");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((DailyLoginTokenEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, long, string, bool, DateTimeOffset?, DateOnly>(((ValueComparer<Guid>)(((IProperty)accountId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(accountId)), ((ValueComparer<long>)(((IProperty)tokenId).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(tokenId)), (source.GetCurrentValue<string>(token_type) == null ? null : ((ValueComparer<string>)(((IProperty)token_type).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(token_type))), ((ValueComparer<bool>)(((IProperty)claimed).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(claimed)), (source.GetCurrentValue<DateTimeOffset?>(claimedOn) == null ? null : ((ValueComparer<DateTimeOffset?>)(((IProperty)claimedOn).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset?>(claimedOn))), ((ValueComparer<DateOnly>)(((IProperty)date).GetValueComparer())).Snapshot(source.GetCurrentValue<DateOnly>(date)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, long>(((ValueComparer<Guid>)(((IProperty)accountId).GetValueComparer())).Snapshot(default(Guid)), ((ValueComparer<long>)(((IProperty)tokenId).GetValueComparer())).Snapshot(default(long))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, long>(default(Guid), default(long)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<string>((source.ContainsKey("token_type") ? ((string)(source["token_type"])) : null)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string>(default(string)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((DailyLoginTokenEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, long, object, object>(((ValueComparer<Guid>)(((IProperty)accountId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(accountId)), ((ValueComparer<long>)(((IProperty)tokenId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<long>(tokenId)), source.GetCurrentValue<Account>(account), source.GetCurrentValue<Rewards>(rewards))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 1,
                relationshipCount: 4,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Tokens");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
