// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public partial class EarthDbContextModel
    {
        private EarthDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b85d924d-2da8-44b1-b144-11c535607e19"), entityTypeCount: 38)
        {
        }

        partial void Initialize()
        {
            var account = AccountEntityType.Create(this);
            var accountVersions = AccountVersionsEntityType.Create(this);
            var encounterBuildplateEF = EncounterBuildplateEFEntityType.Create(this);
            var secret = SecretEntityType.Create(this);
            var sharedBuildplateEF = SharedBuildplateEFEntityType.Create(this);
            var hotbarItem = HotbarItemEntityType.Create(this);
            var templateBuildplateEF = TemplateBuildplateEFEntityType.Create(this);
            var tile = TileEntityType.Create(this);
            var activityLogEntryEF = ActivityLogEntryEFEntityType.Create(this);
            var boostsEF = BoostsEFEntityType.Create(this);
            var activeBoost = ActiveBoostEntityType.Create(this);
            var buildplateEF = BuildplateEFEntityType.Create(this);
            var hotbarEF = HotbarEFEntityType.Create(this);
            var item = ItemEntityType.Create(this);
            var itemJournalEntryEF = ItemJournalEntryEFEntityType.Create(this);
            var nonStackableItemInstanceEF = NonStackableItemInstanceEFEntityType.Create(this);
            var profileEF = ProfileEFEntityType.Create(this);
            var redeemedTappableEF = RedeemedTappableEFEntityType.Create(this);
            var rewards = RewardsEntityType.Create(this);
            var rewards0 = Rewards0EntityType.Create(this);
            var rubies = RubiesEntityType.Create(this);
            var stackableItemEF = StackableItemEFEntityType.Create(this);
            var tokenEF = TokenEFEntityType.Create(this);
            var craftingSlotEF = CraftingSlotEFEntityType.Create(this);
            var craftingSlotsEF = CraftingSlotsEFEntityType.Create(this);
            var smeltingSlot = SmeltingSlotEntityType.Create(this);
            var smeltingSlotsEF = SmeltingSlotsEFEntityType.Create(this);
            var boostActivatedEntryEF = BoostActivatedEntryEFEntityType.Create(this, activityLogEntryEF);
            var journalItemUnlockedEntryEF = JournalItemUnlockedEntryEFEntityType.Create(this, activityLogEntryEF);
            var levelUpEntryEF = LevelUpEntryEFEntityType.Create(this, activityLogEntryEF);
            var rewardedActivityLogEntryEF = RewardedActivityLogEntryEFEntityType.Create(this, activityLogEntryEF);
            var journalItemUnlockedTokenEF = JournalItemUnlockedTokenEFEntityType.Create(this, tokenEF);
            var rewardedTokenEF = RewardedTokenEFEntityType.Create(this, tokenEF);
            var craftingCompletedEntryEF = CraftingCompletedEntryEFEntityType.Create(this, rewardedActivityLogEntryEF);
            var smeltingCompletedEntryEF = SmeltingCompletedEntryEFEntityType.Create(this, rewardedActivityLogEntryEF);
            var tappableEntryEF = TappableEntryEFEntityType.Create(this, rewardedActivityLogEntryEF);
            var dailyLoginTokenEF = DailyLoginTokenEFEntityType.Create(this, rewardedTokenEF);
            var levelUpTokenEF = LevelUpTokenEFEntityType.Create(this, rewardedTokenEF);

            AccountVersionsEntityType.CreateForeignKey1(accountVersions, account);
            SharedBuildplateEFEntityType.CreateForeignKey1(sharedBuildplateEF, account);
            HotbarItemEntityType.CreateForeignKey1(hotbarItem, sharedBuildplateEF);
            ActivityLogEntryEFEntityType.CreateForeignKey1(activityLogEntryEF, account);
            BoostsEFEntityType.CreateForeignKey1(boostsEF, account);
            ActiveBoostEntityType.CreateForeignKey1(activeBoost, boostsEF);
            BuildplateEFEntityType.CreateForeignKey1(buildplateEF, account);
            HotbarEFEntityType.CreateForeignKey1(hotbarEF, account);
            ItemEntityType.CreateForeignKey1(item, hotbarEF);
            ItemJournalEntryEFEntityType.CreateForeignKey1(itemJournalEntryEF, account);
            NonStackableItemInstanceEFEntityType.CreateForeignKey1(nonStackableItemInstanceEF, account);
            ProfileEFEntityType.CreateForeignKey1(profileEF, account);
            RedeemedTappableEFEntityType.CreateForeignKey1(redeemedTappableEF, account);
            RewardsEntityType.CreateForeignKey1(rewards, rewardedActivityLogEntryEF);
            Rewards0EntityType.CreateForeignKey1(rewards0, rewardedTokenEF);
            RubiesEntityType.CreateForeignKey1(rubies, profileEF);
            StackableItemEFEntityType.CreateForeignKey1(stackableItemEF, account);
            TokenEFEntityType.CreateForeignKey1(tokenEF, account);
            CraftingSlotEFEntityType.CreateForeignKey1(craftingSlotEF, craftingSlotsEF);
            CraftingSlotsEFEntityType.CreateForeignKey1(craftingSlotsEF, account);
            SmeltingSlotEntityType.CreateForeignKey1(smeltingSlot, smeltingSlotsEF);
            SmeltingSlotsEFEntityType.CreateForeignKey1(smeltingSlotsEF, account);

            AccountEntityType.CreateAnnotations(account);
            AccountVersionsEntityType.CreateAnnotations(accountVersions);
            EncounterBuildplateEFEntityType.CreateAnnotations(encounterBuildplateEF);
            SecretEntityType.CreateAnnotations(secret);
            SharedBuildplateEFEntityType.CreateAnnotations(sharedBuildplateEF);
            HotbarItemEntityType.CreateAnnotations(hotbarItem);
            TemplateBuildplateEFEntityType.CreateAnnotations(templateBuildplateEF);
            TileEntityType.CreateAnnotations(tile);
            ActivityLogEntryEFEntityType.CreateAnnotations(activityLogEntryEF);
            BoostsEFEntityType.CreateAnnotations(boostsEF);
            ActiveBoostEntityType.CreateAnnotations(activeBoost);
            BuildplateEFEntityType.CreateAnnotations(buildplateEF);
            HotbarEFEntityType.CreateAnnotations(hotbarEF);
            ItemEntityType.CreateAnnotations(item);
            ItemJournalEntryEFEntityType.CreateAnnotations(itemJournalEntryEF);
            NonStackableItemInstanceEFEntityType.CreateAnnotations(nonStackableItemInstanceEF);
            ProfileEFEntityType.CreateAnnotations(profileEF);
            RedeemedTappableEFEntityType.CreateAnnotations(redeemedTappableEF);
            RewardsEntityType.CreateAnnotations(rewards);
            Rewards0EntityType.CreateAnnotations(rewards0);
            RubiesEntityType.CreateAnnotations(rubies);
            StackableItemEFEntityType.CreateAnnotations(stackableItemEF);
            TokenEFEntityType.CreateAnnotations(tokenEF);
            CraftingSlotEFEntityType.CreateAnnotations(craftingSlotEF);
            CraftingSlotsEFEntityType.CreateAnnotations(craftingSlotsEF);
            SmeltingSlotEntityType.CreateAnnotations(smeltingSlot);
            SmeltingSlotsEFEntityType.CreateAnnotations(smeltingSlotsEF);
            BoostActivatedEntryEFEntityType.CreateAnnotations(boostActivatedEntryEF);
            JournalItemUnlockedEntryEFEntityType.CreateAnnotations(journalItemUnlockedEntryEF);
            LevelUpEntryEFEntityType.CreateAnnotations(levelUpEntryEF);
            RewardedActivityLogEntryEFEntityType.CreateAnnotations(rewardedActivityLogEntryEF);
            JournalItemUnlockedTokenEFEntityType.CreateAnnotations(journalItemUnlockedTokenEF);
            RewardedTokenEFEntityType.CreateAnnotations(rewardedTokenEF);
            CraftingCompletedEntryEFEntityType.CreateAnnotations(craftingCompletedEntryEF);
            SmeltingCompletedEntryEFEntityType.CreateAnnotations(smeltingCompletedEntryEF);
            TappableEntryEFEntityType.CreateAnnotations(tappableEntryEF);
            DailyLoginTokenEFEntityType.CreateAnnotations(dailyLoginTokenEF);
            LevelUpTokenEFEntityType.CreateAnnotations(levelUpTokenEF);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
