// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models.Global;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class HotbarItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Global.SharedBuildplateEF+HotbarItem",
                typeof(SharedBuildplateEF.HotbarItem),
                baseEntityType,
                propertyCount: 6,
                foreignKeyCount: 1,
                keyCount: 1);

            var sharedBuildplateEFId = runtimeEntityType.AddProperty(
                "SharedBuildplateEFId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            sharedBuildplateEFId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<Guid>(0) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : entry.ReadShadowValue<Guid>(0))),
                Guid (IInternalEntry entry) => entry.ReadShadowValue<Guid>(0),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(sharedBuildplateEFId, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(sharedBuildplateEFId, 0));
            sharedBuildplateEFId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            sharedBuildplateEFId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            sharedBuildplateEFId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(sharedBuildplateEFId));
            sharedBuildplateEFId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var __synthesizedOrdinal = runtimeEntityType.AddProperty(
                "__synthesizedOrdinal",
                typeof(int),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            __synthesizedOrdinal.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && entry.ReadShadowValue<int>(1) == 0 ? entry.ReadTemporaryValue<int>(1) : entry.ReadShadowValue<int>(1))),
                int (IInternalEntry entry) => entry.ReadShadowValue<int>(1),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(__synthesizedOrdinal, 1),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(__synthesizedOrdinal, 1));
            __synthesizedOrdinal.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            __synthesizedOrdinal.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            __synthesizedOrdinal.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(__synthesizedOrdinal));
            __synthesizedOrdinal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var count = runtimeEntityType.AddProperty(
                "Count",
                typeof(int),
                propertyInfo: typeof(SharedBuildplateEF.HotbarItem).GetProperty("Count", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SharedBuildplateEF.HotbarItem).GetField("<Count>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            count.SetGetter(
                int (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Count(instance),
                bool (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Count(instance) == 0);
            count.SetSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, int value) =>
                {
                    HotbarItemUnsafeAccessors.Count(instance) = value;
                    return instance;
                });
            count.SetMaterializationSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, int value) =>
                {
                    HotbarItemUnsafeAccessors.Count(instance) = value;
                    return instance;
                });
            count.SetAccessors(
                int (IInternalEntry entry) => HotbarItemUnsafeAccessors.Count(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                int (IInternalEntry entry) => HotbarItemUnsafeAccessors.Count(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(count, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(count));
            count.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            count.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            count.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var instanceId = runtimeEntityType.AddProperty(
                "InstanceId",
                typeof(Guid?),
                propertyInfo: typeof(SharedBuildplateEF.HotbarItem).GetProperty("InstanceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SharedBuildplateEF.HotbarItem).GetField("<InstanceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            instanceId.SetGetter(
                Guid? (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.InstanceId(instance),
                bool (SharedBuildplateEF.HotbarItem instance) => !(HotbarItemUnsafeAccessors.InstanceId(instance).HasValue));
            instanceId.SetSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, Guid? value) =>
                {
                    HotbarItemUnsafeAccessors.InstanceId(instance) = value;
                    return instance;
                });
            instanceId.SetMaterializationSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, Guid? value) =>
                {
                    HotbarItemUnsafeAccessors.InstanceId(instance) = value;
                    return instance;
                });
            instanceId.SetAccessors(
                Guid? (IInternalEntry entry) => HotbarItemUnsafeAccessors.InstanceId(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                Guid? (IInternalEntry entry) => HotbarItemUnsafeAccessors.InstanceId(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                Guid? (IInternalEntry entry) => entry.ReadOriginalValue<Guid?>(instanceId, 3),
                Guid? (IInternalEntry entry) => entry.GetCurrentValue<Guid?>(instanceId));
            instanceId.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            instanceId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            instanceId.SetComparer(new NullableValueComparer<Guid>(instanceId.TypeMapping.Comparer));
            instanceId.SetKeyComparer(new NullableValueComparer<Guid>(instanceId.TypeMapping.KeyComparer));
            instanceId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var uuid = runtimeEntityType.AddProperty(
                "Uuid",
                typeof(Guid),
                propertyInfo: typeof(SharedBuildplateEF.HotbarItem).GetProperty("Uuid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SharedBuildplateEF.HotbarItem).GetField("<Uuid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            uuid.SetGetter(
                Guid (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Uuid(instance),
                bool (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Uuid(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            uuid.SetSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, Guid value) =>
                {
                    HotbarItemUnsafeAccessors.Uuid(instance) = value;
                    return instance;
                });
            uuid.SetMaterializationSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, Guid value) =>
                {
                    HotbarItemUnsafeAccessors.Uuid(instance) = value;
                    return instance;
                });
            uuid.SetAccessors(
                Guid (IInternalEntry entry) => HotbarItemUnsafeAccessors.Uuid(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                Guid (IInternalEntry entry) => HotbarItemUnsafeAccessors.Uuid(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(uuid, 4),
                Guid (IInternalEntry entry) => entry.GetCurrentValue<Guid>(uuid));
            uuid.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            uuid.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            uuid.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var wear = runtimeEntityType.AddProperty(
                "Wear",
                typeof(int),
                propertyInfo: typeof(SharedBuildplateEF.HotbarItem).GetProperty("Wear", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SharedBuildplateEF.HotbarItem).GetField("<Wear>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            wear.SetGetter(
                int (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Wear(instance),
                bool (SharedBuildplateEF.HotbarItem instance) => HotbarItemUnsafeAccessors.Wear(instance) == 0);
            wear.SetSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, int value) =>
                {
                    HotbarItemUnsafeAccessors.Wear(instance) = value;
                    return instance;
                });
            wear.SetMaterializationSetter(
                SharedBuildplateEF.HotbarItem (SharedBuildplateEF.HotbarItem instance, int value) =>
                {
                    HotbarItemUnsafeAccessors.Wear(instance) = value;
                    return instance;
                });
            wear.SetAccessors(
                int (IInternalEntry entry) => HotbarItemUnsafeAccessors.Wear(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                int (IInternalEntry entry) => HotbarItemUnsafeAccessors.Wear(((SharedBuildplateEF.HotbarItem)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(wear, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(wear));
            wear.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            wear.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            wear.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { sharedBuildplateEFId, __synthesizedOrdinal });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SharedBuildplateEFId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var hotbar = principalEntityType.AddNavigation("Hotbar",
                runtimeForeignKey,
                onDependent: false,
                typeof(SharedBuildplateEF.HotbarItem[]),
                propertyInfo: typeof(SharedBuildplateEF).GetProperty("Hotbar", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SharedBuildplateEF).GetField("<Hotbar>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            hotbar.SetGetter(
                SharedBuildplateEF.HotbarItem[] (SharedBuildplateEF instance) => SharedBuildplateEFUnsafeAccessors.Hotbar(instance),
                bool (SharedBuildplateEF instance) => SharedBuildplateEFUnsafeAccessors.Hotbar(instance) == null);
            hotbar.SetSetter(
                SharedBuildplateEF (SharedBuildplateEF instance, SharedBuildplateEF.HotbarItem[] value) =>
                {
                    SharedBuildplateEFUnsafeAccessors.Hotbar(instance) = value;
                    return instance;
                });
            hotbar.SetMaterializationSetter(
                SharedBuildplateEF (SharedBuildplateEF instance, SharedBuildplateEF.HotbarItem[] value) =>
                {
                    SharedBuildplateEFUnsafeAccessors.Hotbar(instance) = value;
                    return instance;
                });
            hotbar.SetAccessors(
                SharedBuildplateEF.HotbarItem[] (IInternalEntry entry) => SharedBuildplateEFUnsafeAccessors.Hotbar(((SharedBuildplateEF)(entry.Entity))),
                SharedBuildplateEF.HotbarItem[] (IInternalEntry entry) => SharedBuildplateEFUnsafeAccessors.Hotbar(((SharedBuildplateEF)(entry.Entity))),
                null,
                SharedBuildplateEF.HotbarItem[] (IInternalEntry entry) => entry.GetCurrentValue<SharedBuildplateEF.HotbarItem[]>(hotbar));
            hotbar.SetPropertyIndexes(
                index: 1,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 3,
                storeGenerationIndex: -1);
            hotbar.SetCollectionAccessor<SharedBuildplateEF, SharedBuildplateEF.HotbarItem[], SharedBuildplateEF.HotbarItem>(
                SharedBuildplateEF.HotbarItem[] (SharedBuildplateEF entity) => SharedBuildplateEFUnsafeAccessors.Hotbar(entity),
                (SharedBuildplateEF entity, SharedBuildplateEF.HotbarItem[] collection) => SharedBuildplateEFUnsafeAccessors.Hotbar(entity) = ((SharedBuildplateEF.HotbarItem[])collection),
                (SharedBuildplateEF entity, SharedBuildplateEF.HotbarItem[] collection) => SharedBuildplateEFUnsafeAccessors.Hotbar(entity) = ((SharedBuildplateEF.HotbarItem[])collection),
                null,
                null);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var sharedBuildplateEFId = runtimeEntityType.FindProperty("SharedBuildplateEFId");
            var __synthesizedOrdinal = runtimeEntityType.FindProperty("__synthesizedOrdinal");
            var count = runtimeEntityType.FindProperty("Count");
            var instanceId = runtimeEntityType.FindProperty("InstanceId");
            var uuid = runtimeEntityType.FindProperty("Uuid");
            var wear = runtimeEntityType.FindProperty("Wear");
            var key = runtimeEntityType.FindKey(new[] { sharedBuildplateEFId, __synthesizedOrdinal });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SharedBuildplateEF.HotbarItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int, int, Guid?, Guid, int>(((ValueComparer<Guid>)(((IProperty)sharedBuildplateEFId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(sharedBuildplateEFId)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(__synthesizedOrdinal)), ((ValueComparer<int>)(((IProperty)count).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(count)), (source.GetCurrentValue<Guid?>(instanceId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)instanceId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(instanceId))), ((ValueComparer<Guid>)(((IProperty)uuid).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(uuid)), ((ValueComparer<int>)(((IProperty)wear).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(wear)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, int>(((ValueComparer<Guid>)(((IProperty)sharedBuildplateEFId).GetValueComparer())).Snapshot(default(Guid)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, int>(default(Guid), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<Guid, int>((source.ContainsKey("SharedBuildplateEFId") ? ((Guid)(source["SharedBuildplateEFId"])) : new Guid("00000000-0000-0000-0000-000000000000")), (source.ContainsKey("__synthesizedOrdinal") ? ((int)(source["__synthesizedOrdinal"])) : 0)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, int>(default(Guid), default(int)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SharedBuildplateEF.HotbarItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int>(((ValueComparer<Guid>)(((IProperty)sharedBuildplateEFId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(sharedBuildplateEFId)), ((ValueComparer<int>)(((IProperty)__synthesizedOrdinal).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(__synthesizedOrdinal)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:ContainerColumnName", "Hotbar");
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SharedBuildplates");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
