// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class ItemJournalEntryEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref Guid AccountId(ItemJournalEntryEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemId>k__BackingField")]
        public static extern ref Guid ItemId(ItemJournalEntryEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AmountCollected>k__BackingField")]
        public static extern ref int AmountCollected(ItemJournalEntryEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FirstSeen>k__BackingField")]
        public static extern ref DateTimeOffset FirstSeen(ItemJournalEntryEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastSeen>k__BackingField")]
        public static extern ref DateTimeOffset LastSeen(ItemJournalEntryEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(ItemJournalEntryEF @this);
    }
}
