// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class LevelUpTokenUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Level>k__BackingField")]
        public static extern ref int Level(LevelUpTokenEF @this);
    }
}
