// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class NonStackableItemInstanceEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref Guid AccountId(NonStackableItemInstanceEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemId>k__BackingField")]
        public static extern ref Guid ItemId(NonStackableItemInstanceEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<InstanceId>k__BackingField")]
        public static extern ref Guid InstanceId(NonStackableItemInstanceEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Wear>k__BackingField")]
        public static extern ref int Wear(NonStackableItemInstanceEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(NonStackableItemInstanceEF @this);
    }
}
