// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProfileEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Player.ProfileEF",
                typeof(ProfileEF),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 2,
                foreignKeyCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ProfileEF).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfileEF).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (ProfileEF instance) => ProfileEFUnsafeAccessors.Id(instance),
                bool (ProfileEF instance) => ProfileEFUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                ProfileEF (ProfileEF instance, Guid value) =>
                {
                    ProfileEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                ProfileEF (ProfileEF instance, Guid value) =>
                {
                    ProfileEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && ProfileEFUnsafeAccessors.Id(((ProfileEF)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : ProfileEFUnsafeAccessors.Id(((ProfileEF)(entry.Entity))))),
                Guid (IInternalEntry entry) => ProfileEFUnsafeAccessors.Id(((ProfileEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var experience = runtimeEntityType.AddProperty(
                "Experience",
                typeof(int),
                propertyInfo: typeof(ProfileEF).GetProperty("Experience", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfileEF).GetField("<Experience>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            experience.SetGetter(
                int (ProfileEF instance) => ProfileEFUnsafeAccessors.Experience(instance),
                bool (ProfileEF instance) => ProfileEFUnsafeAccessors.Experience(instance) == 0);
            experience.SetSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Experience(instance) = value;
                    return instance;
                });
            experience.SetMaterializationSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Experience(instance) = value;
                    return instance;
                });
            experience.SetAccessors(
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Experience(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Experience(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(experience, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(experience));
            experience.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            experience.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            experience.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var health = runtimeEntityType.AddProperty(
                "Health",
                typeof(int),
                propertyInfo: typeof(ProfileEF).GetProperty("Health", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfileEF).GetField("<Health>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            health.SetGetter(
                int (ProfileEF instance) => ProfileEFUnsafeAccessors.Health(instance),
                bool (ProfileEF instance) => ProfileEFUnsafeAccessors.Health(instance) == 0);
            health.SetSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Health(instance) = value;
                    return instance;
                });
            health.SetMaterializationSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Health(instance) = value;
                    return instance;
                });
            health.SetAccessors(
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Health(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Health(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(health, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(health));
            health.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            health.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            health.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var level = runtimeEntityType.AddProperty(
                "Level",
                typeof(int),
                propertyInfo: typeof(ProfileEF).GetProperty("Level", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfileEF).GetField("<Level>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            level.SetGetter(
                int (ProfileEF instance) => ProfileEFUnsafeAccessors.Level(instance),
                bool (ProfileEF instance) => ProfileEFUnsafeAccessors.Level(instance) == 0);
            level.SetSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Level(instance) = value;
                    return instance;
                });
            level.SetMaterializationSetter(
                ProfileEF (ProfileEF instance, int value) =>
                {
                    ProfileEFUnsafeAccessors.Level(instance) = value;
                    return instance;
                });
            level.SetAccessors(
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Level(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => ProfileEFUnsafeAccessors.Level(((ProfileEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(level, 3),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(level));
            level.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            level.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            level.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Id") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var account = declaringEntityType.AddNavigation("Account",
                runtimeForeignKey,
                onDependent: true,
                typeof(Account),
                propertyInfo: typeof(ProfileEF).GetProperty("Account", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfileEF).GetField("<Account>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            account.SetGetter(
                Account (ProfileEF instance) => ProfileEFUnsafeAccessors.Account(instance),
                bool (ProfileEF instance) => ProfileEFUnsafeAccessors.Account(instance) == null);
            account.SetSetter(
                ProfileEF (ProfileEF instance, Account value) =>
                {
                    ProfileEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetMaterializationSetter(
                ProfileEF (ProfileEF instance, Account value) =>
                {
                    ProfileEFUnsafeAccessors.Account(instance) = value;
                    return instance;
                });
            account.SetAccessors(
                Account (IInternalEntry entry) => ProfileEFUnsafeAccessors.Account(((ProfileEF)(entry.Entity))),
                Account (IInternalEntry entry) => ProfileEFUnsafeAccessors.Account(((ProfileEF)(entry.Entity))),
                null,
                Account (IInternalEntry entry) => entry.GetCurrentValue<Account>(account));
            account.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            var profile = principalEntityType.AddNavigation("Profile",
                runtimeForeignKey,
                onDependent: false,
                typeof(ProfileEF),
                propertyInfo: typeof(Account).GetProperty("Profile", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Account).GetField("<Profile>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            profile.SetGetter(
                ProfileEF (Account instance) => AccountUnsafeAccessors.Profile(instance),
                bool (Account instance) => AccountUnsafeAccessors.Profile(instance) == null);
            profile.SetSetter(
                Account (Account instance, ProfileEF value) =>
                {
                    AccountUnsafeAccessors.Profile(instance) = value;
                    return instance;
                });
            profile.SetMaterializationSetter(
                Account (Account instance, ProfileEF value) =>
                {
                    AccountUnsafeAccessors.Profile(instance) = value;
                    return instance;
                });
            profile.SetAccessors(
                ProfileEF (IInternalEntry entry) => AccountUnsafeAccessors.Profile(((Account)(entry.Entity))),
                ProfileEF (IInternalEntry entry) => AccountUnsafeAccessors.Profile(((Account)(entry.Entity))),
                null,
                ProfileEF (IInternalEntry entry) => entry.GetCurrentValue<ProfileEF>(profile));
            profile.SetPropertyIndexes(
                index: 8,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 9,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var experience = runtimeEntityType.FindProperty("Experience");
            var health = runtimeEntityType.FindProperty("Health");
            var level = runtimeEntityType.FindProperty("Level");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var account = runtimeEntityType.FindNavigation("Account");
            var rubies = runtimeEntityType.FindNavigation("Rubies");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ProfileEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int, int, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<int>)(((IProperty)experience).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(experience)), ((ValueComparer<int>)(((IProperty)health).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(health)), ((ValueComparer<int>)(((IProperty)level).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(level)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ProfileEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), source.GetCurrentValue<Account>(account), source.GetCurrentValue<Rubies>(rubies))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Profiles");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
