// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Solace.DB.Models.Common;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class RewardsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Buildplates>k__BackingField")]
        public static extern ref Guid[] Buildplates(Rewards @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Challenges>k__BackingField")]
        public static extern ref string[] Challenges(Rewards @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExperiencePoints>k__BackingField")]
        public static extern ref int ExperiencePoints(Rewards @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Items>k__BackingField")]
        public static extern ref Dictionary<Guid, int> Items(Rewards @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Level>k__BackingField")]
        public static extern ref int? Level(Rewards @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Rubies>k__BackingField")]
        public static extern ref int Rubies(Rewards @this);
    }
}
