// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class RubiesUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Earned>k__BackingField")]
        public static extern ref int Earned(Rubies @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Purchased>k__BackingField")]
        public static extern ref int Purchased(Rubies @this);
    }
}
