// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models.Player.Workshop;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class SmeltingSlotUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Locked>k__BackingField")]
        public static extern ref bool Locked(SmeltingSlot @this);
    }
}
