// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using Solace.DB.Models.Global;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TemplateBuildplateEFEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Solace.DB.Models.Global.TemplateBuildplateEF",
                typeof(TemplateBuildplateEF),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Id(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && TemplateBuildplateEFUnsafeAccessors.Id(((TemplateBuildplateEF)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : TemplateBuildplateEFUnsafeAccessors.Id(((TemplateBuildplateEF)(entry.Entity))))),
                Guid (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Id(((TemplateBuildplateEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var blocksPerMeter = runtimeEntityType.AddProperty(
                "BlocksPerMeter",
                typeof(int),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("BlocksPerMeter", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<BlocksPerMeter>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            blocksPerMeter.SetGetter(
                int (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(instance) == 0);
            blocksPerMeter.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(instance) = value;
                    return instance;
                });
            blocksPerMeter.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(instance) = value;
                    return instance;
                });
            blocksPerMeter.SetAccessors(
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.BlocksPerMeter(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(blocksPerMeter, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(blocksPerMeter));
            blocksPerMeter.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            blocksPerMeter.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            blocksPerMeter.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.SetGetter(
                string (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Name(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, string value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, string value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Name(((TemplateBuildplateEF)(entry.Entity))),
                string (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Name(((TemplateBuildplateEF)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            name.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var night = runtimeEntityType.AddProperty(
                "Night",
                typeof(bool),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("Night", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<Night>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            night.SetGetter(
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Night(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Night(instance) == false);
            night.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, bool value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Night(instance) = value;
                    return instance;
                });
            night.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, bool value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Night(instance) = value;
                    return instance;
                });
            night.SetAccessors(
                bool (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Night(((TemplateBuildplateEF)(entry.Entity))),
                bool (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Night(((TemplateBuildplateEF)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(night, 3),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(night));
            night.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            night.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            night.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var offset = runtimeEntityType.AddProperty(
                "Offset",
                typeof(int),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("Offset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<Offset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            offset.SetGetter(
                int (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Offset(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Offset(instance) == 0);
            offset.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Offset(instance) = value;
                    return instance;
                });
            offset.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Offset(instance) = value;
                    return instance;
                });
            offset.SetAccessors(
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Offset(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Offset(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(offset, 4),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(offset));
            offset.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            offset.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            offset.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var previewObjectId = runtimeEntityType.AddProperty(
                "PreviewObjectId",
                typeof(Guid),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("PreviewObjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<PreviewObjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            previewObjectId.SetGetter(
                Guid (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            previewObjectId.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(instance) = value;
                    return instance;
                });
            previewObjectId.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(instance) = value;
                    return instance;
                });
            previewObjectId.SetAccessors(
                Guid (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(((TemplateBuildplateEF)(entry.Entity))),
                Guid (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.PreviewObjectId(((TemplateBuildplateEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(previewObjectId, 5),
                Guid (IInternalEntry entry) => entry.GetCurrentValue<Guid>(previewObjectId));
            previewObjectId.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            previewObjectId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            previewObjectId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var serverDataObjectId = runtimeEntityType.AddProperty(
                "ServerDataObjectId",
                typeof(Guid),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("ServerDataObjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<ServerDataObjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            serverDataObjectId.SetGetter(
                Guid (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            serverDataObjectId.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(instance) = value;
                    return instance;
                });
            serverDataObjectId.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, Guid value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(instance) = value;
                    return instance;
                });
            serverDataObjectId.SetAccessors(
                Guid (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(((TemplateBuildplateEF)(entry.Entity))),
                Guid (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.ServerDataObjectId(((TemplateBuildplateEF)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(serverDataObjectId, 6),
                Guid (IInternalEntry entry) => entry.GetCurrentValue<Guid>(serverDataObjectId));
            serverDataObjectId.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            serverDataObjectId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            serverDataObjectId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var size = runtimeEntityType.AddProperty(
                "Size",
                typeof(int),
                propertyInfo: typeof(TemplateBuildplateEF).GetProperty("Size", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TemplateBuildplateEF).GetField("<Size>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            size.SetGetter(
                int (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Size(instance),
                bool (TemplateBuildplateEF instance) => TemplateBuildplateEFUnsafeAccessors.Size(instance) == 0);
            size.SetSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Size(instance) = value;
                    return instance;
                });
            size.SetMaterializationSetter(
                TemplateBuildplateEF (TemplateBuildplateEF instance, int value) =>
                {
                    TemplateBuildplateEFUnsafeAccessors.Size(instance) = value;
                    return instance;
                });
            size.SetAccessors(
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Size(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => TemplateBuildplateEFUnsafeAccessors.Size(((TemplateBuildplateEF)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(size, 7),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(size));
            size.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            size.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            size.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var blocksPerMeter = runtimeEntityType.FindProperty("BlocksPerMeter");
            var name = runtimeEntityType.FindProperty("Name");
            var night = runtimeEntityType.FindProperty("Night");
            var offset = runtimeEntityType.FindProperty("Offset");
            var previewObjectId = runtimeEntityType.FindProperty("PreviewObjectId");
            var serverDataObjectId = runtimeEntityType.FindProperty("ServerDataObjectId");
            var size = runtimeEntityType.FindProperty("Size");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((TemplateBuildplateEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, int, string, bool, int, Guid, Guid, int>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<int>)(((IProperty)blocksPerMeter).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(blocksPerMeter)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), ((ValueComparer<bool>)(((IProperty)night).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(night)), ((ValueComparer<int>)(((IProperty)offset).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(offset)), ((ValueComparer<Guid>)(((IProperty)previewObjectId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(previewObjectId)), ((ValueComparer<Guid>)(((IProperty)serverDataObjectId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(serverDataObjectId)), ((ValueComparer<int>)(((IProperty)size).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(size)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((TemplateBuildplateEF)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TemplateBuildplates");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
