// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Solace.DB.Models;
using Solace.DB.Models.Player;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Solace.DB.CompiledModels
{
    public static class TokenEFUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref Guid AccountId(TokenEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenId>k__BackingField")]
        public static extern ref long TokenId(TokenEF @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(TokenEF @this);
    }
}
