<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.DB.Postgres/Solace.DB.Postgres.csproj" />
    <ProjectReference Include="../Solace.DB.Sqlite/Solace.DB.Sqlite.csproj" />
    <ProjectReference Include="../Solace.DB/Solace.DB.csproj" />
  </ItemGroup>

</Project>
