<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1707;CA1869;MA0002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Solace.Common.Asp\Solace.Common.Asp.csproj" />
    <ProjectReference Include="..\..\src\Solace.Db.Earth\Solace.Db.Earth.csproj" />
  </ItemGroup>

</Project>
