syntax = "proto3";

option csharp_namespace = "Solace.ObjectStore";

package objectstore;

service ObjectStoreService {
    rpc GetTotalSize (GetTotalSizeRequest) returns (GetTotalSizeResponse);

    rpc DeleteAll (DeleteAllRequest) returns (DeleteAllResponse);

    rpc StoreObject (stream StoreObjectRequest) returns (StoreObjectResponse);

    rpc GetObject (GetObjectRequest) returns (stream GetObjectResponse);

    rpc DeleteObject (DeleteObjectRequest) returns (DeleteObjectResponse);
}

message GetTotalSizeRequest {
}

message GetTotalSizeResponse {
    int64 total_size = 1;
}

message DeleteAllRequest {
}

message DeleteAllResponse {
}

message StoreObjectRequest {
    bytes chunk_data = 1;
}

message StoreObjectResponse {
    fixed64 idLow = 1;
    fixed64 idHigh = 2;
}

message GetObjectRequest {
    fixed64 idLow = 1;
    fixed64 idHigh = 2;
}

message GetObjectResponse {
    int64 total_length = 1; 
    
    bytes chunk_data = 2;
}

message DeleteObjectRequest{
    fixed64 idLow = 1;
    fixed64 idHigh = 2;
}

message DeleteObjectResponse {
    bool success = 1;
}
