<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Solace.Common\Solace.Common.csproj" />
  </ItemGroup>

</Project>
