<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1707;MA0002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Solace.EventBus.Client\Solace.EventBus.Client.csproj" />
    <ProjectReference Include="..\..\src\Solace.EventBus.Server\Solace.EventBus.Server.csproj" />
  </ItemGroup>

</Project>
