<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>aspnet-Solace_AdminPanel-157240ba-1021-45b3-9a98-e9c28d696417</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AssemblyName>AdminPanel</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="MoveDependenciesToShared" AfterTargets="Publish" Condition="'$(UseSharedLibs)' == 'true'">

    <PropertyGroup>
      <SharedLibsDir>$([System.IO.Path]::GetFullPath('$(PublishDir)..\shared_libs'))\</SharedLibsDir>
    </PropertyGroup>

    <ItemGroup>
      <FilesToMove Include="$(PublishDir)*.dll;$(PublishDir)*.pdb" Exclude="$(PublishDir)$(TargetName).dll;$(PublishDir)$(TargetName).pdb" />
    </ItemGroup>

    <MakeDir Directories="$(SharedLibsDir)" />

    <Copy SourceFiles="@(FilesToMove)" DestinationFolder="$(SharedLibsDir)" SkipUnchangedFiles="true" Retries="5" RetryDelayMilliseconds="500" />

    <Delete Files="@(FilesToMove)" />

  </Target>

  <PropertyGroup Condition="'$(UseSharedLibs)' == 'true'">
    <DefineConstants>$(DefineConstants);USE_SHARED_LIBS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor3D" />
    <PackageReference Include="MCeToJava" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.BuildplateImporter/Solace.BuildplateImporter.csproj" />
    <ProjectReference Include="../Solace.BuildplateRenderer/Solace.BuildplateRenderer.csproj" />
    <ProjectReference Include="../Solace.Common/Solace.Common.csproj" />
    <ProjectReference Include="../Solace.DB/Solace.DB.csproj" />
    <ProjectReference Include="../Solace.ObjectStore.Client/Solace.ObjectStore.Client.csproj" />
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
    <ProjectReference Include="../Solace.StaticData/Solace.StaticData.csproj" />
  </ItemGroup>

</Project>
