<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <AssemblyName>TileRenderer</AssemblyName>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <Target Name="MoveDependenciesToShared" AfterTargets="Publish" Condition="'$(UseSharedLibs)' == 'true'">

    <PropertyGroup>
      <SharedLibsDir>$([System.IO.Path]::GetFullPath('$(PublishDir)..\shared_libs'))\</SharedLibsDir>
    </PropertyGroup>

    <ItemGroup>
      <FilesToMove Include="$(PublishDir)*.dll;$(PublishDir)*.pdb" Exclude="$(PublishDir)$(TargetName).dll;$(PublishDir)$(TargetName).pdb" />
    </ItemGroup>

    <MakeDir Directories="$(SharedLibsDir)" />

    <Copy SourceFiles="@(FilesToMove)" DestinationFolder="$(SharedLibsDir)" SkipUnchangedFiles="true" Retries="5" RetryDelayMilliseconds="500" />

    <Delete Files="@(FilesToMove)" />

  </Target>

  <PropertyGroup Condition="'$(UseSharedLibs)' == 'true'">
    <DefineConstants>$(DefineConstants);USE_SHARED_LIBS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="NetTopologySuite.Features" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../Protos/vector_tile.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Solace.ServiceDefaults/Solace.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Solace.EventBus.Client\Solace.EventBus.Client.csproj" />
    <ProjectReference Include="..\Solace.StaticData\Solace.StaticData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tagMap.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
